# YouWo support checkout is pending owner verification.
# The inherited SideScreen funding entries were removed to avoid sending
# HarmonyScreen support payments to the wrong recipient. Upstream credit
# remains in LICENSE and NOTICE. Configure a verified YouWo link before enabling.
